### ISSUE TITLE
make tests actually run

### ISSUE THREAD

**Issue by ryan-williams** [danvk/jss#9]
seems like they're [looking for `*.spec` files](https://github.com/danvk/jss/blob/b75a28ab9e0454a0dac9a780136234d67344a0fd/tests/integration_tests.py#L18) that don't exist?

**Comment by danvk** [comment]
Whoops, looks like `*.spec` was being gitignored by github's Python defaults. Fixed by 41534e5ec788ac1782ea9f4d303f2c5c28dcd4d4
